### ISSUE TITLE
Error at broadcast_ops_gpu.cc:38

### ISSUE THREAD

**Issue by Luo-Liang** [facebookincubator/gloo#101]
Hello, 

I decided to move to container. I have the latest clone of the Caffe2 repo and built the docker image using caffe2/docker/ubuntu16.04-cuda8-cudnn7 DockerFIle.

Everything is fine until this:

liangluo@n38:~/caffe2/docker/ubuntu-16.04-cuda8-cudnn7-all-options$ sh run.sh 2 0 3456
Ignoring @/caffe2/caffe2/contrib/nccl:nccl_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops_gpu as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:file_store_handler_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:redis_store_handler_ops as it is not a valid file.
INFO:resnet50_trainer:Running on GPUs: [0]
INFO:resnet50_trainer:Using epoch size: 49984
INFO:data_parallel_model:Parallelizing model for devices: [0]
INFO:data_parallel_model:Create input and model training operators
INFO:data_parallel_model:Model for GPU : 0
INFO:data_parallel_model:Adding gradient operators
INFO:data_parallel_model:Add gradient all-reduces for SyncSGD
**WARNING:data_parallel_model:Distributed broadcast of computed params is not implemented yet**
INFO:data_parallel_model:Post-iteration operators for updating params
INFO:data_parallel_model:Calling optimizer builder function
INFO:data_parallel_model:Add initial parameter sync
**WARNING:data_parallel_model:------- DEPRECATED API, please use data_parallel_model.OptimizeGradientMemory() -----**
WARNING:memonger:NOTE: Executing memonger to optimize gradient memory
**INFO:memonger:Memonger memory optimization took 0.0321569442749 secs**
Traceback for operator 1212 in network resnet50_init
/usr/local/caffe2/python/data_parallel_model.py:1051
/usr/local/caffe2/python/data_parallel_model.py:1060
/usr/local/caffe2/python/data_parallel_model.py:964
/usr/local/caffe2/python/data_parallel_model.py:323
resnet50_trainer.py:443
resnet50_trainer.py:605
resnet50_trainer.py:609
Traceback (most recent call last):
  File "resnet50_trainer.py", line 609, in <module>
    main()
  File "resnet50_trainer.py", line 605, in main
    Train(args)
  File "resnet50_trainer.py", line 446, in Train
    workspace.RunNetOnce(train_model.param_init_net)
  File "/usr/local/caffe2/python/workspace.py", line 207, in RunNetOnce
    StringifyProto(net),
  File "/usr/local/caffe2/python/workspace.py", line 190, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at broadcast_ops_gpu.cc:38] false. Unhandled type: int Error from operator:
input: "broadcast_0_cw" input: "gpu_0/label" output: "gpu_0/label" name: "label" type: "Broadcast" arg { name: "status_blob" s: "broadcast_label_status" } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "GLOO" control_input: "gpu_0/data"

Where run.sh is simply:

nvidia-docker run --rm  --net=host -it docker.sampa:5000/caffe2 bash -c "cd /caffe2/caffe2/python/examples && python resnet50_trainer.py --train_data null --image_size 256 
--gpus 0 --batch_size 32 --num_labels 1000 --epoch_size 50000 --num_epochs 10 --num_shards $1 --shard_id $2 --redis_host 10.2.5.45 --distributed_transport tcp --distributed_interfaces ib0 --run_id $3"

I intend to train with IPOIB so I used TCP and IB0. I bolded some warnings. I compiled with USE_IBVERBS but I didn't actually use it. Let me know if there is something clearly wrong.

Thanks!

**Comment by Luo-Liang** [comment]
The offending code is 

template <class Context>
void BroadcastOp<Context>::initializeAlgorithm() {
  if (init_.template IsType<float>()) {
    algorithm_.reset(new ::gloo::CudaBroadcastOneToAll<float>(
        init_.context, init_.template getOutputs<float>(), init_.size, root_));
  } else if (init_.template IsType<float16>()) {
    algorithm_.reset(new ::gloo::CudaBroadcastOneToAll<::gloo::float16>(
        init_.context,
        init_.template getOutputs<::gloo::float16>(),
        init_.size,
        root_));
  } else {
    CAFFE_ENFORCE(false, "Unhandled type: ", init_.meta.name());
  }
}

I don't know where that int comes from. Please check my argument - they may be wrong? I also tried specifically --dtype float and it is the same result.

**Comment by Luo-Liang** [comment]
The problem goes away when im using real data instead of synthetic ones.
